// generate-card.js
const fs = require('fs');
const { createCanvas } = require('canvas');

// 获取当前时间用于卡片显示
const now = new Date();
const timeString = now.toLocaleString();

// 创建画布
const width = 800;
const height = 400;
const canvas = createCanvas(width, height);
const ctx = canvas.getContext('2d');

// 绘制背景
ctx.fillStyle = '#2d333b';
ctx.fillRect(0, 0, width, height);

// 绘制标题
ctx.font = 'bold 30px Arial';
ctx.fillStyle = '#ffffff';
ctx.fillText('GitHub Readme Card Test', 50, 60);

// 绘制分隔线
ctx.strokeStyle = '#444c56';
ctx.lineWidth = 2;
ctx.beginPath();
ctx.moveTo(50, 80);
ctx.lineTo(width - 50, 80);
ctx.stroke();

// 绘制内容
ctx.font = '20px Arial';
ctx.fillStyle = '#adbac7';
ctx.fillText(`This is a test card generated by GitHub Actions`, 50, 120);
ctx.fillText(`Current time: ${timeString}`, 50, 160);

// 绘制GitHub Actions状态
ctx.fillStyle = '#46954a';
ctx.fillRect(50, 200, 200, 40);
ctx.fillStyle = '#ffffff';
ctx.font = 'bold 18px Arial';
ctx.fillText('Action Successful!', 60, 226);

// 保存为PNG文件
const out = fs.createWriteStream('card.png');
const stream = canvas.createPNGStream();
stream.pipe(out);

out.on('finish', () => {
    console.log('Card image generated successfully: card.png');

    // 同时生成一个SVG版本（可选）
    const svgContent = `
    <svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
      <rect width="100%" height="100%" fill="#2d333b"/>
      <text x="50" y="60" font-family="Arial" font-size="30" font-weight="bold" fill="#ffffff">
        GitHub Readme Card Test
      </text>
      <line x1="50" y1="80" x2="${width - 50}" y2="80" stroke="#444c56" stroke-width="2"/>
      <text x="50" y="120" font-family="Arial" font-size="20" fill="#adbac7">
        This is a test card generated by GitHub Actions
      </text>
      <text x="50" y="160" font-family="Arial" font-size="20" fill="#adbac7">
        Current time: ${timeString}
      </text>
      <rect x="50" y="200" width="200" height="40" fill="#46954a"/>
      <text x="60" y="226" font-family="Arial" font-size="18" font-weight="bold" fill="#ffffff">
        Action Successful!
      </text>
    </svg>
  `;

    fs.writeFileSync('card.svg', svgContent);
    console.log('SVG version also generated: card.svg');
});