name: Test Card Generation

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: "0 * * * *" # 每小时运行一次测试

jobs:
  generate-card:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install canvas

      - name: Generate card
        run: node generate-card.js

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-card
          path: |
            card.png
            card.svg