name: Test Card Generation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  generate-card:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm install node-fetch canvas animejs

      - name: Generate card
        run: node generate-card.js

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-card
          path: |
            card.svg

      - name: Commit and push assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用默认的 GITHUB_TOKEN
        run: |
          # 配置 Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # 移动生成的卡片文件到 assets 目录
          mkdir -p assets
          [ -f "card.svg" ] && mv card.svg assets/

          # 仅添加卡片文件，忽略其他未跟踪文件
          git add assets/

          # 检查是否有实际变更
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Auto-generated card: $(date +'%Y-%m-%d %H:%M')"
            git push
          fi